#%%
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
email = input("Enter your email address: ")
phone_number = input("Enter your phone number: ")
job_title = input("Enter your job title: ")
id_number = input("Enter your ID number: ")
hair_color = input("Enter your hair color: ")
eye_color = input("Enter your eye color: ")
month = input("Enter the current month: ")
training = input("Enter is you are training (true or false): ")
print("The ID Card is:")
print("--------------------------------")
print(f'[{last_name.upper()}]'',  'f'[{first_name}]')
print(f'[{job_title}]')
print(f'ID: {id_number}')
print('')
print(f'[{email}]')
print(f'[{phone_number}]')
print('')
print(f'Hair: {hair_color}''\t'f'Eye Color: {eye_color}')
print(f'Month: {month}''\t'f'Training: {training}')
print("--------------------------------")